name: allen

dependencies:
  - python=2.7
  - numpy=1.13.*
  - matplotlib=2.1.*
  - scipy=1.0.0
  - scikit-learn
  - seaborn
  - pandas
  - jupyter
  - jupyterlab=0.3
  - notebook
  - pip:
    - allensdk
    - xgboost